image:
  repository: ghcr.io/akuity/rollouts-demo
  pullPolicy: IfNotPresent
  tag: blue

replicaCount: 1

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

podAnnotations: {}

# Artificial delays to slow down updates for demo purposes
minReadySeconds: 10
preStopSleepSeconds: 10

resources:
  limits:
    cpu: 100m
    memory: 32Mi
  requests:
    cpu: 10m
    memory: 32Mi

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
