apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: kargo-blue-green
spec:
  vars:
  - name: repoURL
    value: https://github.com/jessesuen/kargo-blue-green.git
  - name: image
    value: ghcr.io/akuity/rollouts-demo
  - name: replicaCount
    value: "3"

  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: main
        path: ./src

  # Determine which of the blue or green service is desired to be
  # active based on what the ingress is currently pointing to.
  - uses: yaml-parse
    as: ingressService
    config:
      path: ./src/env/kargo-bgapp-ingress/values.yaml
      outputs:
      - name: desired
        fromExpression: 'ingress.service.name == "app-blue" ? "green" : "blue"'
      - name: previous
        fromExpression: 'ingress.service.name == "app-blue" ? "blue" : "green"'

  # Scale up the desired env with new image
  - uses: yaml-update
    config:
      path: ./src/env/kargo-bgapp-${{ task.outputs.ingressService.desired }}/values.yaml
      updates:
      - key: app.image.tag
        value: ${{ imageFrom( vars.image ).Tag }}
      - key: app.replicaCount
        value: ${{ vars.replicaCount }}
  - uses: git-commit
    config:
      path: ./src
      message: "1/3: Update `app-${{ task.outputs.ingressService.desired }}` to `${{vars.image}}:${{imageFrom(vars.image)}}``, scale to ${{vars.replicaCount}} replicas"
  - uses: git-push
    config:
      path: ./src
  - uses: argocd-update
    config:
      apps:
      - name: kargo-bgapp-${{ task.outputs.ingressService.desired }}
        sources:
        - repoURL: ${{ vars.repoURL }}

  # Switch the ingress to point to the new desired app
  - uses: yaml-update
    config:
      path: ./src/env/kargo-bgapp-ingress/values.yaml
      updates:
      - key: ingress.service.name
        value: app-${{ task.outputs.ingressService.desired }}
  - uses: git-commit
    config:
      path: ./src
      message: "2/3: Update ingress to `app-${{ task.outputs.ingressService.desired }}`"
  - uses: git-push
    config:
      path: ./src
  - uses: argocd-update
    config:
      apps:
      - name: kargo-bgapp-ingress
        sources:
        - repoURL: ${{ vars.repoURL }}

  # Scale down the previous env with new image
  - uses: yaml-update
    config:
      path: ./src/env/kargo-bgapp-${{ task.outputs.ingressService.previous }}/values.yaml
      updates:
      - key: app.replicaCount
        value: "0"
  - uses: git-commit
    config:
      path: ./src
      message: "3/3: Scale down `app-${{ task.outputs.ingressService.previous }}` to 0"
  - uses: git-push
    config:
      path: ./src
  - uses: argocd-update
    config:
      apps:
      - name: kargo-bgapp-${{ task.outputs.ingressService.previous }}
        sources:
        - repoURL: ${{ vars.repoURL }}
