apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kargo-blue-green
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  destinations:
  - name: '*'
    namespace: kargo-blue-green
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://github.com/*/kargo-blue-green.git
